### ISSUE TITLE
Контент для 8.9.10 застревает в очереди

### ISSUE THREAD

**Issue by Niklan** [Druki-ru/website#29]
Остаётся единственный в очереди и не вливается. Надо выяснить в чём там ошибка. Все остальные при этом успешно обновляются.

https://github.com/Druki-ru/content/blob/master/docs/ru/drupal/8/releases/release-8.9.10.md

**Comment by Niklan** [comment]
Ошибка в фронт маттере файла:

```yaml
metatags:
title: 'Drupal 8.9.10: Список изменений'
description: 'Список изменений Drupal 8.9.10.'
```

Отступы отсутствуют у вложенных итемов.
